# Generated by Django 3.2.6 on 2021-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='Country',
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
