# Generated by Django 3.2.6 on 2021-09-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210907_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='specialism',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
