# Generated by Django 3.2.6 on 2021-09-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('users', '0002_auto_20210905_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cedula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desired_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, through='users.UserLanguages', to='profiles.Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, through='users.UserSkills', to='profiles.Skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='soft_skills',
            field=models.ManyToManyField(blank=True, null=True, through='users.UserSoftSkills', to='profiles.SoftSkill'),
        ),
    ]
