# Generated by Django 3.2.6 on 2021-09-06 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_country'),
        ('users', '0004_auto_20210905_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nearby_search',
            field=models.BooleanField(default=True),
        ),
    ]
