# Generated by Django 3.2.6 on 2021-09-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_numbre',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
