# Generated by Django 3.2.6 on 2021-09-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileCompany',
        ),
    ]
