# Generated by Django 3.2.6 on 2021-09-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecompany',
            name='phone_number',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profilecompany',
            name='web_site',
            field=models.URLField(blank=True, default=' ', null=True),
        ),
    ]
